
(()=>{
const E=createMonthlyTrainingEngine(),A=createShapleyAnalysis(E),R=createScenarioRegistry(),$=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
let data=JSON.parse($('#precomputed').textContent),worker=null,token=0;
const codeSHA256=data.codeSHA256;
const f=(v,d=2)=>v.toLocaleString('zh-CN',{maximumFractionDigits:d}),pct=v=>(100*v).toFixed(2)+'%',pp=v=>(v>=0?'+':'')+(100*v).toFixed(2)+' pp';
const colors={base:'#2864a0',silent:'#b56625',local:'#087f76',both:'#7953ae',all:'#aa4545'};
const fields=[['stepSeconds','step 时长 / s',.001,600],['silentDetectSeconds','静默即时检出延迟 / s',0,3600],['silentRecoverySeconds','静默恢复准备 / s',0,7200],['silentFallbackDays','静默兜底发现 / 天',0,365],['silentTarget','静默即时检出率目标 / %',0,100],['recoveryTarget','中断/亚健康恢复目标 / min',0,120],['intervalTarget','检查点周期目标 / s',.001,7200],['saveTarget','保存阻塞目标 / s',0,10],['fitTarget','单卡等效 FIT 目标值',0,100000]];
for(const [key,label,min,max]of fields){const lab=document.createElement('label');lab.textContent=label;const input=document.createElement('input');Object.assign(input,{id:'cfg-'+key,type:'number',min,max,step:'any',value:Number(data.config[key].toFixed(6))});input.setAttribute('aria-label',label);lab.append(input);$('#controls').append(lab);}
function selectControl(key,label,choices){const lab=document.createElement('label');lab.textContent=label;const sel=document.createElement('select');sel.id='cfg-'+key;for(const [v,t]of choices){const op=document.createElement('option');op.value=v;op.textContent=t;sel.append(op);}if(!Array.from(sel.options).some(o=>o.value===String(data.config[key]))){const op=document.createElement('option');op.value=data.config[key];op.textContent=data.config[key]+' 次 · 自定义';sel.append(op);}sel.value=data.config[key];lab.append(sel);$('#controls').append(lab);}
selectControl('fallbackDistribution','兜底发现时间分布',[['fixed','固定延迟（均值近似）'],['exponential','指数分布（给定均值）']]);selectControl('trials','每组合模拟轨迹数',[[512,'512 次 · 快速检查'],[2048,'2048 次 · 默认'],[8192,'8192 次 · 提高精度']]);
for(const q of A.qValues){const op=document.createElement('option');op.value=q;op.textContent=q+'%';$('#coverage').append(op);}$('#coverage').value='95';
for(const [i,factor]of data.factors.entries()){const lab=document.createElement('label');lab.className='choice';const cb=document.createElement('input');cb.type='checkbox';cb.checked=true;cb.dataset.factor=i;cb.addEventListener('input',coalition);lab.append(cb,document.createTextNode(factor.name));$('#choices').append(lab);}
function readConfig(){const c=Object.fromEntries(fields.map(([k])=>[k,+$('#cfg-'+k).value]));c.trials=+$('#cfg-trials').value;c.fallbackDistribution=$('#cfg-fallbackDistribution').value;c.model=panels.readModel();return c;}
const panels=createSystemPanels({E,A,R,getData:()=>data,codeSHA256,$,f,pct,table,canvas,el,text,importConfig:c=>{if(worker)throw new Error('请先停止正在运行的计算');for(const [k]of fields)$('#cfg-'+k).value=c[k];if(!Array.from($('#cfg-trials').options).some(o=>o.value===String(c.trials))){const op=document.createElement('option');op.value=c.trials;op.textContent=c.trials+' 次 · 自定义';$('#cfg-trials').append(op);}$('#cfg-trials').value=c.trials;$('#cfg-fallbackDistribution').value=c.fallbackDistribution;}});
document.querySelectorAll('#controls input,#controls select').forEach(x=>x.addEventListener('input',()=>{$('#status').textContent=worker?'正在计算已提交参数；新修改需再次刷新。':'参数已修改，图表保留上次完整结果。';$('#error').textContent='';}));
function table(id,rows){$(id).replaceChildren(...rows.map(cells=>{const tr=document.createElement('tr');for(const value of cells){const td=document.createElement('td');td.textContent=value;tr.append(td);}return tr;}));}
const selected=()=>data.scale.find(r=>r.n===+$('#size').value);
function coalition(){const r=selected();let mask=0;document.querySelectorAll('[data-factor]').forEach(e=>{if(e.checked)mask|=1<<Number(e.dataset.factor);});const v=r.coalitions[mask];$('#coalition-result').textContent='组合 '+mask+' / 255：正确交付产出 '+pct(v.mean)+'；相对基线 '+pp(v.mean-r.base.mean)+'；均值 95% 采样区间 '+pct(Math.max(0,v.low))+'–'+pct(Math.min(1,v.high))+'。';}
function render(){const r=selected();$('#sample-meta').textContent='每组合 '+f(data.config.trials)+' 次 · '+f(data.totalJobs)+' 个情景';$('#base-value').textContent=pct(r.base.mean);$('#all-value').textContent=pct(r.all.mean);$('#gain-value').textContent=pp(r.gain.mean);for(const [id,v]of [['base-ci',r.base],['all-ci',r.all]])$('#'+id).textContent='95%采样区间 '+pct(Math.max(0,v.low))+'–'+pct(Math.min(1,v.high));$('#balance').textContent='贡献加和残差 '+(r.residual*100).toExponential(1)+' pp';const ranked=[...r.contributions].sort((a,b)=>b.shapley.mean-a.shapley.mean);$('#main-insight').textContent=f(r.n/10000)+' 万卡：在这组目标下，Shapley 贡献最大的方向是“'+ranked[0].name+'”（'+pp(ranked[0].shapley.mean)+'），其次是“'+ranked[1].name+'”（'+pp(ranked[1].shapley.mean)+'）。这包含了各方向分得的交互收益，不等同于单项改动效果。';
table('#rank-table',ranked.map(v=>[v.name+'：'+v.target,pp(v.shapley.mean),Math.abs(r.gain.mean)>1e-8?pct(v.shapley.mean/r.gain.mean):'—',pp(v.standalone.mean),pp(v.last.mean)]));
$('#silent-assumption').textContent='已应用：即时发现 '+f(data.config.silentDetectSeconds)+' s，恢复准备 '+f(data.config.silentRecoverySeconds)+' s，兜底 '+f(data.config.silentFallbackDays)+' 天（'+(data.config.fallbackDistribution==='fixed'?'固定延迟':'指数分布均值')+'）';
table('#snapshot',[['周期','30 天 / 720 h'],['中断发现',data.baseline.hardDetect+'% 自动发现 '+data.baseline.hardSeconds+' s；其余 '+data.baseline.fallbackMinutes+' min 超时发现'],['恢复基线','全局 '+data.baseline.globalMinutes+' min / 局部 '+data.baseline.localMinutes+' min'],['基线静默即时检出率','0%；漏检仍有 '+f(data.config.silentFallbackDays)+' 天兜底'],['干净检查点保留','永久，不因年龄删除；step 状态不自动持久化'],['基线检查点',data.baseline.intervalSeconds+' s 周期 / '+data.baseline.saveSeconds+' s 阻塞'],...fields.map(([k,label])=>[label,f(data.config[k],6)]),...panels.fields.map(([k,label])=>[label,k.startsWith('fit')?f(data.baseline.fits[+k.slice(3)],6):String(data.baseline[k])]),['每组合轨迹数',f(data.config.trials)]]);

$('#assumptions').replaceChildren(...data.assumptions.map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));drawRank();drawSweep();drawScale();coverage();coalition();panels.render();}
function el(tag,a={},txt){const x=document.createElementNS(NS,tag);for(const k in a)x.setAttribute(k,a[k]);if(txt!==undefined)x.textContent=txt;return x;}
function text(svg,x,y,t,a={}){svg.append(el('text',{x,y,fill:'#172d42','font-size':13,...a},t));}
function canvas(id,height,title){const root=$(id),w=Math.max(700,Math.floor(root.getBoundingClientRect().width)),svg=el('svg',{viewBox:'0 0 '+w+' '+height,role:'img','aria-label':title});root.replaceChildren(svg);return {svg,w};}
function drawRank(){const r=selected(),items=[...r.contributions].sort((a,b)=>b.shapley.mean-a.shapley.mean),{svg,w}=canvas('#rank-plot',605,'Shapley 改进贡献');const L=285,R=115,T=65,B=548,lo=Math.min(0,...items.map(v=>v.shapley.low)),hi=Math.max(.01,...items.map(v=>v.shapley.high)),x=v=>L+(w-L-R)*(v-lo)/(hi-lo);text(svg,22,28,f(r.n/10000)+' 万卡 · Shapley 贡献（已分配交互收益）',{'font-size':17,'font-weight':600});for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;svg.append(el('line',{x1:x(v),x2:x(v),y1:T-15,y2:B,stroke:'#dbe4ec'}));text(svg,x(v),574,Math.abs(v*100)<.05?'0.0':(v*100).toFixed(1),{'text-anchor':'middle'});}items.forEach((v,i)=>{const cy=T+i*59,color=v.shapley.high<0?'#aa4545':v.shapley.low<=0?'#7c8e9c':'#087f76';text(svg,22,cy+6,(i+1)+'. '+v.name,{'font-size':14,'font-weight':500});text(svg,22,cy+24,v.target,{fill:'#5a6b7c','font-size':12});const rect=el('rect',{x:Math.min(x(0),x(v.shapley.mean)),y:cy-7,width:Math.max(1,Math.abs(x(v.shapley.mean)-x(0))),height:23,fill:color,'data-rank':v.id});rect.append(el('title',{},v.name+'：'+pp(v.shapley.mean)+'；95%区间 ['+pp(v.shapley.low)+', '+pp(v.shapley.high)+']'));svg.append(rect);svg.append(el('line',{x1:x(v.shapley.low),x2:x(v.shapley.high),y1:cy+4,y2:cy+4,stroke:'#172d42'}));for(const a of [v.shapley.low,v.shapley.high])svg.append(el('line',{x1:x(a),x2:x(a),y1:cy,y2:cy+8,stroke:'#172d42'}));text(svg,w-15,cy+10,pp(v.shapley.mean),{'text-anchor':'end','font-size':14});});text(svg,(L+w-R)/2,599,'正确交付产出率贡献 / 百分点',{'text-anchor':'middle'});}
function axes(svg,w,T,B){const L=72,R=26;for(const v of [0,.25,.5,.75,1]){const y=B-(B-T)*v;svg.append(el('line',{x1:L,x2:w-R,y1:y,y2:y,stroke:'#dbe4ec'}));text(svg,L-10,y+4,(v*100)+'%',{'text-anchor':'end'});}text(svg,0,0,'正确交付产出率（%）',{transform:'translate(20 '+((T+B)/2)+') rotate(-90)','text-anchor':'middle'});}
function line(svg,points,x,y,color){const d=points.map((p,i)=>(i?'L':'M')+x(p.x)+','+y(p.r.mean)).join(' ');const band=points.map((p,i)=>(i?'L':'M')+x(p.x)+','+y(Math.min(1,p.r.high))).join(' ')+' '+[...points].reverse().map(p=>'L'+x(p.x)+','+y(Math.max(0,p.r.low))).join(' ')+' Z';svg.append(el('path',{d:band,fill:color,opacity:.1}));svg.append(el('path',{d,fill:'none',stroke:color,'stroke-width':2.5}));}
function drawSweep(){const n=+$('#size').value,points=data.sweep.find(s=>s.n===n).points,{svg,w}=canvas('#sweep-plot',410,'静默即时检出率扫描'),L=72,R=26,T=65,B=320,x=q=>L+(w-L-R)*q/100,y=v=>B-(B-T)*v;axes(svg,w,T,B);text(svg,L,26,f(n/10000)+' 万卡 · 静默即时检测（保留兜底机制）',{'font-size':17,'font-weight':600});for(const [mode,label,offset]of [['global','全局恢复',230],['local','局部容错',110]]){const color=colors[mode==='global'?'base':'local'];svg.append(el('line',{x1:w-offset,x2:w-offset+20,y1:47,y2:47,stroke:color,'stroke-width':3}));text(svg,w-offset+25,51,label,{'font-size':12});line(svg,points.map(p=>({x:p.q,r:p[mode]})),x,y,color);const r=points.find(p=>p.q===+$('#coverage').value)[mode];svg.append(el('circle',{cx:x(+$('#coverage').value),cy:y(r.mean),r:4,fill:'white',stroke:color,'stroke-width':2}));}for(const q of [0,20,40,60,80,100])text(svg,x(q),B+25,q+'%',{'text-anchor':q===0?'start':q===100?'end':'middle'});text(svg,(L+w-R)/2,B+57,'静默即时检出率（漏检仍可能由兜底发现）',{'text-anchor':'middle'});}
function coverage(){const p=data.sweep.find(s=>s.n===+$('#size').value).points.find(p=>p.q===+$('#coverage').value);table('#coverage-table',[['全局 / '+p.q+'%',pct(p.global.mean),pp(p.globalGain.mean)],['局部 / '+p.q+'%',pct(p.local.mean),pp(p.localGain.mean)]]);}
function drawScale(){const {svg,w}=canvas('#scale-plot',550,'规模与改进组合'),L=72,R=26,T=80,B=315,log=$('#xscale').value==='log',x=n=>L+(w-L-R)*(log?Math.log(n/1000)/Math.log(500):(n-1000)/499000),y=v=>B-(B-T)*v;axes(svg,w,T,B);text(svg,L,25,'30 天 · 五种方案的正确交付产出率',{'font-size':17,'font-weight':600});const series=[['base','全局 · 0%'],['silent','全局 · '+data.config.silentTarget+'%'],['local','局部 · 0%'],['both','局部 · '+data.config.silentTarget+'%'],['all','全部改进']];series.forEach(([k,label],i)=>{const xx=L+i*(w-L-R)/5;svg.append(el('line',{x1:xx,x2:xx+16,y1:50,y2:50,stroke:colors[k],'stroke-width':3}));text(svg,xx+21,54,label,{'font-size':11});line(svg,data.scale.map(r=>({x:r.n,r:r[k]})),x,y,colors[k]);for(const n of A.keyScales){const r=data.scale.find(r=>r.n===n);svg.append(el('circle',{cx:x(n),cy:y(r[k].mean),r:3,fill:'white',stroke:colors[k],'stroke-width':1.5}));}});for(const n of log?[1000,10000,100000,500000]:[1000,100000,200000,300000,400000,500000])text(svg,x(n),B+25,n===1000?'1千':f(n/10000)+'万',{'text-anchor':n===1000?'start':n===500000?'end':'middle'});text(svg,(L+w-R)/2,B+48,'单一训练任务规模 N（卡）',{'text-anchor':'middle'});const top=392,labelW=105,col=(w-L-R-labelW)/4;svg.append(el('rect',{x:L,y:top-16,width:w-L-R,height:153,fill:'#f4f7fa'}));A.keyScales.forEach((n,j)=>text(svg,L+labelW+(j+.5)*col,top,f(n/10000)+' 万卡',{'text-anchor':'middle'}));series.forEach(([k,label],i)=>{text(svg,L+8,top+25+i*24,label,{fill:colors[k],'font-size':12});A.keyScales.forEach((n,j)=>{const v=data.scale.find(r=>r.n===n)[k].mean;text(svg,L+labelW+(j+.5)*col,top+25+i*24,pct(v),{fill:colors[k],'text-anchor':'middle','data-key-label':n,'data-series':k,'data-value':v});});});}
async function digest(s){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
function refresh(){for(const x of document.querySelectorAll('#controls input,#model-controls input'))if(x.value===''||!x.checkValidity()){$('#error').textContent='请检查参数：'+x.getAttribute('aria-label');return;}const c=readConfig();try{A.setup(c);}catch(e){$('#error').textContent=e.message;return;}const submitted=JSON.stringify(c),id=++token;document.body.dataset.recomputed='false';$('#error').textContent='';$('#refresh').disabled=true;$('#stop').hidden=false;$('#progress').hidden=false;$('#progress').value=0;$('#status').textContent='正在枚举组合并模拟训练…';const source='const E=('+createMonthlyTrainingEngine.toString()+')();const A=('+createShapleyAnalysis.toString()+')(E);self.onmessage=e=>{try{const data=A.run(e.data,p=>self.postMessage({type:"progress",p}));self.postMessage({type:"done",data});}catch(e){self.postMessage({type:"error",message:e.message});}};';const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);function end(){if(worker)worker.terminate();worker=null;$('#refresh').disabled=false;$('#stop').hidden=true;$('#progress').hidden=true;}worker.onmessage=async e=>{if(id!==token)return;const m=e.data;if(m.type==='progress'){$('#progress').max=m.p.total;$('#progress').value=m.p.done;$('#status').textContent=m.p.done+'/'+m.p.total+' 情景 · '+f(m.p.n)+' 卡';}if(m.type==='error'){end();$('#error').textContent=m.message;$('#status').textContent='计算未完成，保留上次结果。';}if(m.type==='done'){m.data.codeSHA256=codeSHA256;m.data.scenario=R.scenario(m.data.config,E.version,codeSHA256);m.data.createdAt=new Date().toISOString();try{m.data.scenarioSHA256=await digest(R.canonical(m.data.scenario));m.data.experiment={scenarioSHA256:m.data.scenarioSHA256,scales:m.data.scale.map(r=>r.n),seedPolicy:m.data.seedPolicy,trials:m.data.config.trials,hours:m.data.hours,codeSHA256};m.data.experimentSHA256=await digest(R.canonical(m.data.experiment));}catch(err){end();$('#error').textContent='无法生成实验摘要：'+err.message;return;}if(id!==token)return;data=m.data;end();render();$('#status').textContent=JSON.stringify(readConfig())===submitted?'全部 Shapley 结果已刷新。':'提交时的参数已刷新；另有新修改尚未应用。';document.body.dataset.recomputed='true';}};worker.onerror=e=>{end();$('#error').textContent=e.message;};worker.postMessage(c);}
$('#refresh').addEventListener('click',refresh);$('#stop').addEventListener('click',()=>{if(worker)worker.terminate();worker=null;token++;$('#refresh').disabled=false;$('#stop').hidden=true;$('#progress').hidden=true;$('#status').textContent='已停止，保留上次完整结果。';});$('#size').addEventListener('input',render);$('#coverage').addEventListener('input',()=>{drawSweep();coverage();});$('#xscale').addEventListener('input',drawScale);let last=0;new ResizeObserver(()=>{const w=$('#scale-plot').clientWidth;if(w!==last){last=w;drawRank();drawSweep();drawScale();panels.drawTopology();panels.drawLedger();}}).observe($('#scale-plot'));render();document.body.dataset.ready='true';
})();
