const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert'),path=require('path'),vm=require('vm'),crypto=require('crypto'),{pathToFileURL}=require('url');
const dir=__dirname,file=path.join(dir,'正确有效产出改进分析.html'),expected=require('./Shapley贡献结果.json');
const E=require('./月度训练仿真引擎.js')(),A=require('./Shapley贡献计算.js')(E),R=require('./场景与证据.js')();
const near=(a,b)=>assert(Math.abs(a-b)<1e-10,`${a} != ${b}`),fmt=v=>(100*v).toFixed(2)+'%';
for(const m of fs.readFileSync(file,'utf8').matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g))if(!m[1].includes('application/json'))new vm.Script(m[2]);
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE}),ctx=await browser.newContext({offline:true,deviceScaleFactor:2}),page=await ctx.newPage(),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:1050});await page.goto(pathToFileURL(file).href);await page.waitForFunction(()=>document.body.dataset.ready==='true');
 for(const n of A.keyScales){await page.locator('#size').selectOption(String(n));const row=expected.scale.find(r=>r.n===n);assert.equal(await page.locator('#base-value').textContent(),fmt(row.base.mean));assert.equal(await page.locator('#all-value').textContent(),fmt(row.all.mean));assert.equal(await page.locator('#ledger-table tr').count(),10);}
 checks.push('four key scales match CLI and have conserved ledgers');assert.equal(await page.locator('[data-key-label]').count(),20);checks.push('twenty scale values are labeled');
 await page.locator('#size').selectOption('500000');await page.locator('#coverage').selectOption('0');assert((await page.locator('#coverage-table').textContent()).includes('+0.00 pp'));await page.locator('#coverage').selectOption('95');await page.locator('#xscale').selectOption('log');assert.equal(await page.locator('[data-key-label]').count(),20);await page.locator('#xscale').selectOption('linear');
 await page.locator('#choices').locator('..').evaluate(e=>e.open=true);await page.locator('[data-factor]').evaluateAll(es=>es.forEach(e=>{e.checked=false;e.dispatchEvent(new Event('input'));}));assert((await page.locator('#coalition-result').textContent()).includes(fmt(expected.scale.at(-1).base.mean)));checks.push('coalition explorer and sweep');
 const snap=await page.locator('#snapshot').textContent(),top=await page.locator('#topology-summary').textContent();await page.locator('#model-recoveryDomains').fill('10');assert.equal(await page.locator('#topology-summary').textContent(),top);assert.equal(await page.locator('#snapshot').textContent(),snap);await page.locator('#model-silentPct').fill('101');await page.locator('#refresh').click();assert((await page.locator('#error').textContent()).length>0);await page.locator('#model-silentPct').fill('0.4');checks.push('draft isolation and invalid model inputs');
 const download=async id=>{const task=page.waitForEvent('download');await page.locator(id).click();const item=await task;return JSON.parse(fs.readFileSync(await item.path(),'utf8'));};
 const scenario=await download('#export-scenario');assert.equal(scenario.config.model.recoveryDomains,50);assert.equal(scenario.modelVersion,E.version);const exportResult=await download('#export-result');assert.equal(exportResult.scenarioSHA256,expected.scenarioSHA256);checks.push('export uses applied scenario, not draft');
 const imported={...scenario,config:{...scenario.config,silentTarget:0,model:{...scenario.config.model,recoveryDomains:10}}};await page.locator('#import-scenario').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>document.querySelector('#cfg-silentTarget').value==='0'||document.querySelector('#error').textContent!=='');assert.equal(await page.locator('#cfg-silentTarget').inputValue(),'0');assert.equal(await page.locator('#topology-summary').textContent(),top);checks.push('scenario import is validated and deferred');
 await page.locator('#refresh').click();await page.locator('#stop').click();assert((await page.locator('#status').textContent()).includes('已停止'));assert.equal(await page.locator('#snapshot').textContent(),snap);checks.push('cancel retains complete result');
 await page.locator('#cfg-trials').selectOption('512');await page.locator('#refresh').click();console.log('Offline worker: full 512-trial recomputation with 10 domains and zero silent target');
 await page.waitForFunction(()=>document.body.dataset.recomputed==='true',null,{timeout:360000});assert.equal(await page.locator('#error').textContent(),'');assert((await page.locator('#topology-summary').textContent()).includes('全部 10 域'));
 const updated=await download('#export-result');assert.equal(updated.config.trials,512);assert.equal(updated.config.model.recoveryDomains,10);
 assert.equal(updated.scenarioSHA256,crypto.createHash('sha256').update(R.canonical(updated.scenario)).digest('hex'));assert.equal(updated.experimentSHA256,crypto.createHash('sha256').update(R.canonical(updated.experiment)).digest('hex'));
 const setup=A.setup(updated.config),row=updated.scale.find(r=>r.n===500000);
 for(const [key,mask]of [['base',0],['all',255]]){const sample=E.estimate(500000,setup.params(mask),512);near(sample.delivery.mean,row[key].mean);for(const k of Object.keys(sample.ledger))near(sample.ledger[k],row.diagnostics[key].ledger[k]);}
 near(row.contributions.find(f=>f.id==='silent').shapley.mean,0);checks.push('worker and CLI match for edited model, ledger and zero-change Shapley');checks.push('browser scenario and experiment hashes match Node');
 const direct=await page.evaluate(()=>{const E=createMonthlyTrainingEngine(),A=createShapleyAnalysis(E);return A.run({trials:8,model:{repairSlots:2,rackFIT:1000,placement:'striped',silentMonitorPct:2}},()=>{},[10000]);});
 const local=A.run({trials:8,model:{repairSlots:2,rackFIT:1000,placement:'striped',silentMonitorPct:2}},()=>{},[10000]);let maxNumericDelta=0;function compare(a,b){if(a===b)return;if(typeof a==='number'&&typeof b==='number'){maxNumericDelta=Math.max(maxNumericDelta,Math.abs(a-b));assert(Math.abs(a-b)<1e-9);return;}if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))compare(a[k],b[k]);return;}assert.equal(a,b);}compare(direct,local);checks.push('shared-fault/queue scenario browser and Node agree within 1e-9');
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');const layouts=[];
 for(const width of [1440,1000,390]){await page.setViewportSize({width,height:1050});await page.waitForTimeout(100);const d=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert(d.scroll<=d.client+1);layouts.push(d);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/v4-'+width+'.png'});}checks.push('responsive 1440/1000/390 layouts');
 await page.setViewportSize({width:1440,height:1050});await page.waitForTimeout(100);
 for(const [id,name]of [['rank-plot','Shapley_五十万卡贡献排名'],['sweep-plot','Shapley_静默检出率'],['scale-plot','Shapley_规模对比'],['topology-plot','V4_系统故障域'],['ledger-plot','V4_产出损失账本']]){
  await page.locator('#'+id).screenshot({path:path.join(dir,name+'.png')});const svg=await page.locator('#'+id+' svg').evaluate(e=>{const c=e.cloneNode(true);c.setAttribute('xmlns','http://www.w3.org/2000/svg');const st=document.createElementNS('http://www.w3.org/2000/svg','style');st.textContent='text{font-family:-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}';c.prepend(st);return c.outerHTML;});fs.writeFileSync(path.join(dir,name+'.svg'),svg);
 }
 assert.deepEqual(errors,[]);const result={status:'passed',version:E.version,offline:true,codeSHA256:expected.codeSHA256,checks,maxNumericDelta,layouts,errors};fs.writeFileSync(path.join(dir,'V4交互验证结果.json'),JSON.stringify(result,null,2));console.log(result);await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
