const fs=require('node:fs'),path=require('node:path');
function render(data,events){
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>(100*x).toFixed(2)+'%',pp=x=>(x>=0?'+':'')+(x*100).toFixed(3),num=x=>(x||0).toFixed(3),card=n=>n>=10000?n/10000+'万卡':n+'卡';
const lookup=(id,n)=>data.results.find(r=>r.scenario===id&&r.cards===n),scales=[10000,100000,200000,500000];
const scaleOptions=scales.map(n=>`<option value="${n}" ${n===500000?'selected':''}>${card(n)}</option>`).join('');
const baselineTable=scales.map(n=>{const r=lookup('base',n);return `<tr><td>${card(n)}</td><td>${pct(r.availability)}</td><td><b>${pct(r.mean)}</b> ±${(r.ci95*100).toFixed(3)} pp</td>${['downtime','save','slowdown','rollback','terminalInvalid'].map(k=>`<td>${num(r.ledger[k])}</td>`).join('')}</tr>`}).join('');
const mechanismCards=data.mechanisms.map(m=>{
 const compare=scales.map(n=>{const r=m.scenario?lookup(m.scenario,n):null,cond=m.conditional?data.conditional.find(x=>x.cards===n):null;return `<tr><td>${card(n)}</td><td>${r?pct(r.mean):'未估计'}</td><td>${r?(m.scenario==='base'?'基线内，新增0':pp(r.delta)+' ±'+(r.deltaCi95*100).toFixed(3)+' pp'):'缺少增量参数'}</td><td>${r?num(r.delta*720)+' h':'—'}</td><td>${cond?pp(cond.delta)+' ±'+(cond.ci95*100).toFixed(3)+' pp':'—'}</td></tr>`;}).join('');
 const ids=m.eventIds.join('、');
 return `<details class="mechanism" id="${m.id}"><summary><span class="code">${m.id}</span> ${escape(m.name)} <small>${escape(m.status)}</small></summary><div class="inner"><p class="lead">${escape(m.change)}</p><dl><dt>覆盖事件</dt><dd>${m.eventIds.length}条定义，非零FIT合计 ${num(m.activeFit)}；${escape(ids||'本版不额外计入')}</dd><dt>本轮机器可读参数</dt><dd><code>${escape(JSON.stringify(m.parameters??{role:"基线已有或尚无增量参数"}))}</code></dd><dt>前置条件</dt><dd>${escape(m.prerequisite)}</dd><dt>失败与回退</dt><dd>${escape(m.failure)}</dd><dt>证据等级</dt><dd>${escape(m.confidence)}</dd></dl><div class="scroll"><table><thead><tr><th>规模</th><th>单独启用的有效产出</th><th>相对基线提升 / 95%CI</th><th>每月新增正确计算</th><th>已启用检测后，step额外提升</th></tr></thead><tbody>${compare}</tbody></table></div>${m.scenario&&m.scenario!=='base'?`<p>下方逐事件对照列出“单独启用该机制”的影响。正值表示减少损失；负值可能来自随机波动、机制代价或运行暴露增多。事件贡献不是独立因果效应。公共保存开销单列在表尾，计入该机制总收益。</p><label>规模 <select class="impactScale" data-mechanism="${m.id}">${scaleOptions}</select></label><div class="scroll"><table><thead><tr><th>事件</th><th>直接覆盖</th><th>基线停机 h</th><th>启用后停机 h</th><th>基线计算损失 h</th><th>启用后计算损失 h</th><th>减少总损失 h</th></tr></thead><tbody id="impact-${m.id}"></tbody></table></div>`:'<p>本机制不重复领取基线已有能力的收益；“未估计”不等于技术无效。</p>'}</div></details>`;
}).join('');
const extraChecks=fs.existsSync(path.join(__dirname,'review-checks.json'))?JSON.parse(fs.readFileSync(path.join(__dirname,'review-checks.json'))).checks:[];
const allChecks=[...new Map([...data.checks,...extraChecks].map(c=>[c.name,c])).values()];
const reviewRows=allChecks.map(c=>`<li><b class="positive">通过</b> ${escape(c.name)}</li>`).join('');
const sensitivityTables=['sdcCoverage','elasticSync','stepRollback'].map(kind=>`<h3>${{sdcCoverage:'五十万卡：静默即时检出覆盖率（含step恢复）',elasticSync:'五十万卡：弹性全局协调暂停',stepRollback:'五十万卡：step回滚上限敏感性'}[kind]}</h3><table><thead><tr><th>参数</th><th>有效产出率 / 95%CI</th><th>月末污染 h</th><th>停机 h</th><th>局部容量损失 h</th></tr></thead><tbody>${data.sensitivity.filter(r=>r.kind===kind).map(r=>`<tr><td>${kind==='sdcCoverage'?pct(r.value):r.value+'秒'}</td><td>${pct(r.mean)} ±${(r.ci95*100).toFixed(3)} pp</td><td>${num(r.ledger.terminalInvalid)}</td><td>${num(r.ledger.downtime)}</td><td>${num(r.ledger.localLoss)}</td></tr>`).join('')}</tbody></table>`).join('');
const jsData=JSON.stringify({results:data.results,scenarios:data.scenarios,mechanisms:data.mechanisms,events,shapley:data.shapley}).replace(/</g,'\\u003c');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>故障事件与可靠性机制 · 收益审计 v1</title><style>
:root{--ink:#18313d;--muted:#607582;--line:#d8e3e6;--green:#087b71;--orange:#b76e16;--purple:#6d5da9}*{box-sizing:border-box}body{margin:0;background:#eef3f3;color:var(--ink);font:15px/1.75 -apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif}main{max-width:1380px;margin:auto;padding:35px 32px 90px}header{background:#173d46;color:white;padding:35px;border-radius:16px;margin-bottom:22px}header p{color:#c6dddd;max-width:1000px}h1{font-size:32px;line-height:1.35;margin:12px 0}h2{font-size:23px;margin:5px 0 18px}h3{font-size:17px}p{margin:12px 0}.eyebrow{letter-spacing:2px;font-size:12px}nav{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}nav a{color:#ecffff;border:1px solid #5b8186;padding:4px 12px;border-radius:7px;text-decoration:none}section{background:white;border:1px solid var(--line);border-radius:14px;padding:28px;margin:22px 0}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.metric{padding:20px;background:#f3f8f7;border-radius:10px}.metric b{font-size:29px;display:block}.muted,small{color:var(--muted)}.note{padding:16px 20px;border-left:4px solid var(--orange);background:#fff6e7}.good{border-left-color:var(--green);background:#edf8f4}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px;white-space:nowrap;margin:16px 0}th,td{padding:10px 12px;text-align:left;border-bottom:1px solid var(--line)}th{background:#edf3f5;color:#496571;position:sticky;top:0}td.wrap{white-space:normal;min-width:230px}.positive{color:var(--green)}.negative{color:#b7473c}.code{font:12px monospace;color:var(--green);padding:3px 6px;background:#e9f4f1;border-radius:4px}summary{cursor:pointer;padding:16px;font-weight:600}.mechanism{border:1px solid var(--line);border-radius:10px;margin:12px 0}.inner{padding:0 20px 20px}.lead{font-size:16px;color:#244754}dt{font-weight:600;margin-top:10px}dd{margin:0;color:#546d79;overflow-wrap:anywhere}select,input,button{font:inherit;border:1px solid #bfcfd4;padding:6px 10px;border-radius:6px;background:white;color:var(--ink)}label{margin-right:18px}.chart{width:100%;overflow:auto}.chart svg{min-width:760px;max-width:100%;display:block}.legend{display:flex;gap:18px;flex-wrap:wrap;font-size:13px}.chip{width:12px;height:12px;display:inline-block;margin-right:5px}.flow{display:grid;grid-template-columns:1fr 1fr 1fr;gap:15px}.flow>div{border:1px solid var(--line);padding:18px;border-radius:10px;background:#f6f9fa}.formula{font-family:ui-monospace,monospace;background:#f3f6f8;border-radius:8px;padding:15px;overflow:auto}.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.review li{margin:9px 0}a{color:var(--green)}.badge{font-size:12px;padding:2px 7px;background:#edf2f3;border-radius:4px}@media(max-width:800px){main{padding:16px 12px}.cards,.flow{grid-template-columns:1fr}header,section{padding:20px}h1{font-size:26px}summary small{display:block}}
</style></head><body><main>
<header><div class="eyebrow">AI CLUSTER RELIABILITY / 审核版本 01</div><h1>从故障事件到恢复机制<br>逐项解释正确有效产出的改善</h1><p>以最新确认基线为准：中断 96.6% / 亚健康 2% / 静默 1.4%，万卡中断MTBF 30小时。事件库、机制映射、单项收益、组合分摊与审计证据在同一份报告中展开。</p><nav><a href="#requirements">确认口径</a><a href="#model">计算逻辑</a><a href="#overview">收益总览</a><a href="#events">独立事件库</a><a href="#mechanisms">机制逐项审核</a><a href="#shapley">组合贡献</a><a href="#sensitivity">敏感性</a><a href="#review">多轮审视</a></nav></header>
<section id="requirements"><h2>01 / 最近要求与本轮边界</h2><div class="cards"><div class="metric">已确认保存策略<b>300s / 4s</b><small>计算300秒，阻塞保存4秒。停机不保存，恢复重启周期；瞬态重执行和易失step恢复保留周期相位。</small></div><div class="metric">自动恢复与人工兜底<b>3min / 99%</b><small>1%失败额外人工120分钟。平均恢复尝试与人工耗时4.2分钟，不含检测。</small></div><div class="metric">静默兜底发现<b>120h</b><small>固定5天近似平均值。回到错误前最后干净CKPT，保留之前进度。</small></div></div>
<div class="scroll"><table><thead><tr><th>参数/行为</th><th>当前基线</th><th>本轮处理</th></tr></thead><tbody><tr><td>统计对象</td><td>单一作业，集群所有卡参加，30天连续任务</td><td>千卡至50万卡；50域DP为候选能力</td></tr><tr><td>中断发现</td><td>95% 10秒，其余60秒超时</td><td>检测后自动恢复，极少数失败才人工</td></tr><tr><td>亚健康</td><td>降速5%，95% 5分钟发现，其余24小时后结束</td><td>检出后保存当前进度、3分钟恢复、零回滚</td></tr><tr><td>静默</td><td>即时检出0%，5天发现</td><td>目标95%检出；100%只用于敏感性上限</td></tr><tr><td>事件分配</td><td>54条事件 / 18个硬件或根因域</td><td>Core占SDC85%；已审核的12条SDC零预算保留</td></tr><tr><td>旧库失效参数</td><td>旧0.4% SDC、2小时CKPT、10–20分钟恢复</td><td>不参与本轮计算，历史快照留档</td></tr></tbody></table></div><p class="note">这是可审计的条件评估，不是硬件实测结论。FIT为每十亿NPU等效运行小时的业务影响事件率，不是器件物理FIT。硬件拆分与重执行/弹性覆盖仍为先验；本轮没有把旧白皮书引用重新认证为实测证据。</p></section>
<section id="model"><h2>02 / 从事件发生到有效产出的计算逻辑</h2><div class="flow"><div><h3>① 故障事件库</h3>每条事件记录硬件域、类型、FIT和基线后果。<p>λᵢ(N) = N × FITᵢ / 10⁹<br>MTBFᵢ = 1 / λᵢ</p>固定类别总预算，恢复技术不修改源FIT。</div><div><h3>② 机制匹配与回退</h3>中断：检测 → 重执行 → 弹性 → 进程重调度 → 全局CKPT → 人工。<p>只执行已启用且事件适用的机制；成功即停止，失败尝试耗时累加。</p>亚健康保留进度；静默走单独正确性恢复链。</div><div><h3>③ 30天时间仿真</h3>按事件时刻、发现时刻、恢复完成时刻推进。<p>保存、降速、停机、局部容量损失、回滚与月末污染分别计账。</p>同一污染期静默合并，不将每个事件都乘5天。</div></div>
<div class="formula">A运行 = 1 − 全局停机 / 720h<br>A有效 = 月末保留的正确进度 / 720h<br>720h = 正确进度 + 全局停机 + 保存阻塞 + 降速损失 + 局部容量损失 + 已回滚计算 + 月末污染<br>单项提升 ΔAₘ = A有效(仅启用m) − A有效(基线)<br>新增正确计算小时 = 720 × ΔAₘ；表格“pp”表示百分点</div>
<p>无故障保存开销为 4/(300+4)=1.316%；普通中断回滚约为周期一半，即2.5分钟。静默损失由“最后干净进度→发现时剩余计算进度”决定，扣除已单独计账的停机、保存、降速和先前回滚。再次执行这些计算消耗后续时间，不再额外重复扣减。</p><p class="note">DP采用容量等效模型：有效计算倍率 = (可用域数/50) × 亚健康吞吐倍率。域损失只有在其他域能继续产生可保留进度时成立；没有建模梯度同步阻塞、重分片通信、收敛变化、备用卡耗尽和跨域共因。框/机柜/共享存储/未知根因不直接启用局部容错。</p></section>
<section id="overview"><h2>03 / 基线与改进收益总览</h2><p>每个规模、场景 ${data.trials.toLocaleString()} 次30天任务，固定随机种子。95%CI仅表示抽样误差，不能覆盖参数不确定性。与上一份20,000次基线的微小差异来自样本量；已进行逐种子回归验证。</p><div class="scroll"><table><thead><tr><th>规模</th><th>运行可用度</th><th>正确有效产出 / 95%CI</th><th>停机 h</th><th>保存 h</th><th>降速 h</th><th>回滚 h</th><th>月末污染 h</th></tr></thead><tbody>${baselineTable}</tbody></table></div>
<div class="legend"><span><i class="chip" style="background:#8799a2"></i>确认基线</span><span><i class="chip" style="background:#7460ad"></i>静默95%＋step</span><span><i class="chip" style="background:#d39c42"></i>DP弹性单项</span><span><i class="chip" style="background:#0a8076"></i>六机制组合</span></div><div class="chart" id="curve"></div><p class="muted">横轴为单作业卡数，对数刻度；四个重点规模均标注有效产出率。连线仅连接已仿真点，不代表额外精度。</p><label>收益排名规模 <select id="rankScale">${scaleOptions}</select></label><div class="chart" id="rankChart"></div><div class="scroll"><table><thead><tr><th>机制/组合</th><th>有效产出率</th><th>相比基线提升 / 95%CI</th><th>新增正确计算 h/月</th><th>判读</th></tr></thead><tbody id="ranking"></tbody></table></div><p class="note">更快恢复会增加运行暴露，也可能遇到更多静默错误。单项收益可能被正确性问题遮蔽，甚至出现负收益；组合与单项之和通常不相等。快速CKPT目标的保存占比1/61=1.639%，高于基线1.316%，因此小规模下可能下降。</p></section>
<section id="events"><h2>04 / 独立故障事件库 · 初版审核</h2><p>这一张表不混入对应机制。仅显示事件身份、故障率、占比和基线损失；机制到事件的改动放在下一节。0 FIT表示当前预算假设，不表示硬件绝不会发生该类错误。</p><div class="toolbar"><label>规模 <select id="eventScale">${scaleOptions}</select></label><label>类型 <select id="eventType"><option value="all">全部</option><option value="hard">中断</option><option value="slow">亚健康</option><option value="sdc">静默</option></select></label><input id="eventSearch" placeholder="搜索硬件域或事件ID"><label><input type="checkbox" id="hideZero">隐藏零FIT</label></div><p id="eventSummary"></p><div class="scroll"><table><thead><tr><th>事件</th><th>硬件域 / 故障表现</th><th>类型</th><th>FIT</th><th>事件MTBF h</th><th>总占比</th><th>类内占比</th><th>月次数</th><th>单次停机 min*</th><th>月停机 h</th><th>月计算损失 h</th><th>总损失占比**</th><th>归因说明</th></tr></thead><tbody id="eventRows"></tbody></table></div><p class="muted">* 单次停机为该行累计停机/发生次数，静默污染期合并或亚健康漏检时不等于每次恢复耗时。** 分母为全事件停机与计算损失之和，不含公共保存开销。静默长污染损失归给首次污染事件；同一污染期后续SDC不重复领取5天损失。亚健康叠加损失在同一时段活动事件间均分。稀有事件抽样为零不等于真实风险为零。</p><p>此版采用30天有限任务；不得将该月污染损失简单乘12称为连续年度真实停机。每年12个独立重置任务与一个连续全年任务也不是同一种统计对象。</p></section>
<section id="mechanisms"><h2>05 / 可靠性机制库 · 每项修改与收益</h2><p>逐项展开可查看：适用事件、参数变化、前置条件、失败回退、证据等级、各规模单项收益，以及每条事件启用前后的损失。基线已有机制不重复计算新增收益；没有目标参数的硬件改进标记“未估计”。</p>${mechanismCards}</section>
<section id="shapley"><h2>06 / 组合收益不能相加 · Shapley贡献分摊</h2><p>对静默检测、step恢复、重执行、进程重调度、DP弹性、快速CKPT六项枚举全部64个子集；每个子集 ${data.shapley[0].trials} 次模拟。按所有加入顺序的平均边际收益分摊。检测优化两项探索情景未进入这六项组合。</p><div class="formula">φᵢ = Σₛ |S|! (m−|S|−1)! / m! × [A(S∪{i})−A(S)]<br>Σφᵢ = A(全部六项) − A(基线)</div><label>规模 <select id="shapleyScale">${scaleOptions}</select></label><p id="shapleySummary"></p><div class="chart" id="shapleyChart"></div><table><thead><tr><th>机制</th><th>Shapley贡献 / 95%CI</th><th>折算正确计算 h/月</th></tr></thead><tbody id="shapleyRows"></tbody></table><p class="muted">收益函数仍是蒙特卡洛估计；“全子集”不代表真实参数无误差。此处样本量与单项表不同，分摊合计应与本节组合提升核对。依赖检测的step恢复即使单独收益为0，也可能获得组合贡献。</p></section>
<section id="sensitivity"><h2>07 / 对关键假设的敏感性</h2>${sensitivityTables}<p class="note">Core占静默85%。若95%的检出能力实际上只覆盖Core，整体覆盖率最多约 85%×95%=80.75%，不能把它写成全系统95%。本报告主场景的95%假设覆盖全部非零SDC事件，必须逐条证明。step的1秒同样是待校准值，不是由硬件卡数推导出的训练step实测时长。</p></section>
<section id="review"><h2>08 / 多轮审视、证据与下一步</h2><ol class="review">${reviewRows}<li><b>第三轮语义审视：</b>恢复技术不改变输入FIT；亚健康零回滚；旧污染不能被后续即时检出清洗；易失step不能冒充持久化CKPT；公共保存不开票给某个硬件事件。</li><li><b>第四轮收益审视：</b>失败尝试时间进入回退链；不允许既算重执行成功收益又算同次CKPT恢复收益；提供负收益和置信区间；先验与用户确认值分开。</li><li><b>尚未验证的生产边界：</b>误报、检测开销、带宽和备用容量、多个作业、共因故障、硬件寿命分布、SDC发现长尾、训练收敛以及真实DP重构都未纳入；因此DP与step的收益是条件估计。</li></ol>
<p><b>审核优先级：</b>先确认全系统SDC检出覆盖与5天兜底延迟；再核对重执行/进程/DP每条事件的覆盖条件；最后按规模选CKPT周期。不要先把所有恢复时间统一缩短，再把三种恢复收益相加。</p><p>事件与机制的旧白皮书/能力参考仅用于保留来源线索，本次新增的时间、成功率和故障拆分不宣称来自厂商实测。所有本轮输入快照、计算结果、引擎与验证程序均随报告保存。</p>
<p><a href="events.json">独立故障库 JSON</a> · <a href="mechanisms.json">机制库 JSON</a> · <a href="mechanism-policy.json">机制目标参数</a> · <a href="results.json">全部结果与区间</a> · <a href="engine.cjs">逐事件仿真代码</a> · <a href="analyze.cjs">试算与Shapley代码</a> · <a href="inputs.json">本轮输入快照</a> · <a href="review-checks.json">独立复核记录</a></p><p class="muted">复现：在本目录执行 node analyze.cjs，再执行 node review.cjs。生成时间 ${escape(data.createdAt)}。审核报告不覆盖已确认基线和源故障库。界面已做离线脚本与筛选验证，未宣称完成浏览器视觉验收。</p></section>
</main><script>const D=${jsData};
const labels={hard:'中断',slow:'亚健康',sdc:'静默'},names=Object.fromEntries(D.scenarios.map(s=>[s.id,s.name]));
const f=(n,d=3)=>(n||0).toFixed(d),pct=n=>f(n*100,2)+'%',pp=n=>(n>=0?'+':'')+f(n*100),nlabel=n=>n>=10000?n/10000+'万':n;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const loss=e=>(e?.rollback||0)+(e?.slowdown||0)+(e?.localLoss||0)+(e?.terminalInvalid||0),total=e=>loss(e)+(e?.downtime||0);
const get=(id,n)=>D.results.find(r=>r.scenario===id&&r.cards===n);
function curve(){let svg='<svg viewBox="0 0 1100 475" role="img" aria-label="不同规模的正确有效产出率">';const X=n=>75+935*(Math.log10(n)-3)/(Math.log10(500000)-3),Y=v=>330-v*280;
 for(let y=0;y<=100;y+=20)svg+='<line x1="75" y1="'+Y(y/100)+'" x2="1030" y2="'+Y(y/100)+'" stroke="#e0e8eb"/><text x="18" y="'+(Y(y/100)+5)+'" font-size="13">'+y+'%</text>';
 for(const n of [1000,10000,100000,200000,500000])svg+='<text x="'+X(n)+'" y="365" text-anchor="middle" font-size="13">'+nlabel(n)+'卡</text>';
 const colors={base:'#8799a2',sdcStep:'#7460ad',elastic:'#d39c42',combined:'#0a8076'};
 for(const [id,c]of Object.entries(colors)){const rs=D.results.filter(r=>r.scenario===id);svg+='<polyline points="'+rs.map(r=>X(r.cards)+','+Y(r.mean)).join(' ')+'" fill="none" stroke="'+c+'" stroke-width="2.5"/>';for(const r of rs){svg+='<circle cx="'+X(r.cards)+'" cy="'+Y(r.mean)+'" r="4" fill="'+c+'"/>';}}
 for(const [j,id]of Object.keys(colors).entries())for(const n of [10000,100000,200000,500000])svg+='<text x="'+X(n)+'" y="'+(395+j*19)+'" text-anchor="middle" fill="'+colors[id]+'" font-size="12">'+pct(get(id,n).mean)+'</text>';
 svg+='</svg>';document.querySelector('#curve').innerHTML=svg+'<div class="scroll"><table><thead><tr><th>曲线数值标注</th>'+[10000,100000,200000,500000].map(n=>'<th>'+nlabel(n)+'卡</th>').join('')+'</tr></thead><tbody>'+Object.keys(colors).map(id=>'<tr><td style="color:'+colors[id]+'">'+names[id]+'</td>'+[10000,100000,200000,500000].map(n=>'<td>'+pct(get(id,n).mean)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
}
function bars(target,rows){const max=Math.max(1,...rows.map(r=>Math.abs(r.v))),h=rows.length*35+20;let svg='<svg viewBox="0 0 1100 '+h+'" role="img" aria-label="贡献百分点比较">';rows.forEach((r,i)=>{const w=650*Math.abs(r.v)/max,y=i*35+8;svg+='<text x="5" y="'+(y+17)+'" font-size="13">'+esc(r.name)+'</text><rect x="'+(r.v>=0?335:335-w*.2)+'" y="'+y+'" width="'+(r.v>=0?w:w*.2)+'" height="23" rx="3" fill="'+(r.v>=0?'#0a8076':'#c57151')+'"/><text x="'+(r.v>=0?342+w:340)+'" y="'+(y+17)+'" font-size="12">'+(r.v>=0?'+':'')+f(r.v)+' pp</text>';});document.querySelector(target).innerHTML=svg+'</svg>';}
function ranking(){const n=+document.querySelector('#rankScale').value,rs=D.results.filter(r=>r.cards===n&&r.scenario!=='base').sort((a,b)=>b.delta-a.delta);document.querySelector('#ranking').innerHTML=rs.map(r=>'<tr><td>'+esc(names[r.scenario])+'</td><td>'+pct(r.mean)+'</td><td class="'+(r.delta>=0?'positive':'negative')+'">'+pp(r.delta)+' ±'+f(r.deltaCi95*100)+' pp</td><td>'+f(r.delta*720)+'</td><td>'+(Math.abs(r.delta)<=r.deltaCi95?'区间跨0，暂不能区分改善/波动':r.delta>0?'本组假设下改善':'本组假设下下降')+'</td></tr>').join('');bars('#rankChart',rs.map(r=>({name:names[r.scenario],v:r.delta*100})));}
function eventRows(){const n=+document.querySelector('#eventScale').value,t=document.querySelector('#eventType').value,q=document.querySelector('#eventSearch').value.toLowerCase(),z=document.querySelector('#hideZero').checked,b=get('base',n),den=Object.values(b.perEvent).reduce((s,e)=>s+total(e),0);const es=D.events.filter(e=>(t==='all'||e.type===t)&&(!z||e.fit>0)&&(e.id+' '+e.domain).toLowerCase().includes(q));document.querySelector('#eventSummary').textContent='显示 '+es.length+' / 54条。中断96.6%、亚健康2%、静默1.4%；总FIT '+f(D.events.reduce((s,e)=>s+e.fit,0),6)+'。';document.querySelector('#eventRows').innerHTML=es.map(e=>{const v=b.perEvent[e.id]||{};return '<tr><td>'+e.id+'</td><td class="wrap">'+esc(e.domain)+'<br><small>'+esc(e.description)+'</small></td><td>'+labels[e.type]+'</td><td>'+f(e.fit,4)+'</td><td>'+(e.fit?f(1e9/(n*e.fit),2):'∞（零预算）')+'</td><td>'+pct(e.eventShare)+'</td><td>'+pct(e.withinTypeShare)+'</td><td>'+f(v.events)+'</td><td>'+(v.events?f(v.downtime*60/v.events):'—')+'</td><td>'+f(v.downtime)+'</td><td>'+f(loss(v))+'</td><td>'+pct(total(v)/den)+'</td><td class="wrap"><small>'+esc(e.evidence)+' '+esc(e.reviewNote)+'</small></td></tr>';}).join('');}
function impacts(sel){const m=D.mechanisms.find(m=>m.id===sel.dataset.mechanism),n=+sel.value,a=get('base',n),b=get(m.scenario,n);document.querySelector('#impact-'+m.id).innerHTML=D.events.filter(e=>e.fit>0).map(e=>{const x=a.perEvent[e.id]||{},y=b.perEvent[e.id]||{},delta=total(x)-total(y);return '<tr><td>'+e.id+'</td><td>'+(m.eventIds.includes(e.id)?'是':'间接影响')+'</td><td>'+f(x.downtime)+'</td><td>'+f(y.downtime)+'</td><td>'+f(loss(x))+'</td><td>'+f(loss(y))+'</td><td class="'+(delta>=0?'positive':'negative')+'">'+f(delta)+'</td></tr>';}).join('')+'<tr><td>公共保存开销</td><td>共享开销</td><td>—</td><td>—</td><td>'+f(a.ledger.save)+'</td><td>'+f(b.ledger.save)+'</td><td>'+f(a.ledger.save-b.ledger.save)+'</td></tr>';}
function shapley(){const n=+document.querySelector('#shapleyScale').value,s=D.shapley.find(s=>s.cards===n);document.querySelector('#shapleySummary').textContent='本节基线 '+pct(s.baseline)+' → 六机制组合 '+pct(s.combined)+'；总提升 '+pp(s.delta)+' pp，贡献合计相等。';const ps=[...s.players].sort((a,b)=>b.contribution-a.contribution);document.querySelector('#shapleyRows').innerHTML=ps.map(p=>'<tr><td>'+names[p.player]+'</td><td>'+pp(p.contribution)+' ±'+f(p.ci95*100)+' pp</td><td>'+f(p.contribution*720)+'</td></tr>').join('');bars('#shapleyChart',ps.map(p=>({name:names[p.player],v:p.contribution*100})));}
curve();ranking();eventRows();shapley();document.querySelector('#rankScale').addEventListener('change',ranking);document.querySelector('#shapleyScale').addEventListener('change',shapley);for(const id of ['eventScale','eventType','eventSearch','hideZero'])document.getElementById(id).addEventListener('input',eventRows);for(const sel of document.querySelectorAll('.impactScale')){impacts(sel);sel.addEventListener('change',()=>impacts(sel));}
</script></body></html>`;
fs.writeFileSync(path.join(__dirname,'故障事件与可靠性机制收益审核.html'),html);
}
module.exports={render};
if(require.main===module)render(require('./results.json'),require('./events.json').events);
