const fs=require('fs'),path=require('path'),E=require('./engine.cjs');
const combo={sdcDetect:true,step:true,replay:true,process:true,elastic:true,fast:true};
function run(name,opts,patch={},trials=3000){const p={...E.parameters(opts),...patch},values=[],ledger={};let up=0;for(let i=0;i<trials;i++){const r=E.simulate(500000,2,(20261009+Math.imul(i+1,2654435761))>>>0,p,opts);values.push(r.usefulThroughput);up+=r.operationalAvailability;for(const[k,v]of Object.entries(r.ledger))ledger[k]=(ledger[k]||0)+v;}const mean=values.reduce((s,v)=>s+v,0)/trials,ci=1.96*Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/(trials-1)/trials);values.sort((a,b)=>a-b);const row={name,opts,patch,trials,mean,ci95:ci,availability:up/trials,pAtLeast90:values.filter(v=>v>=.9).length/trials,p10:values[Math.floor(.1*trials)],ledger:Object.fromEntries(Object.entries(ledger).map(([k,v])=>[k,v/trials]))};console.log(name,(100*mean).toFixed(3),'±',(100*ci).toFixed(3),'P>=90',(100*row.pAtLeast90).toFixed(1));return row;}
const rows=[];
for(const coverage of [.95,.98,.99,.995,1])for(const seconds of [180,120,60,0])rows.push(run(`组合 SDC${coverage} 全局${seconds}s`,{...combo,sdcCoverage:coverage},{recoveryAttemptSeconds:seconds},2000));
for(const seconds of [180,120,60,30,0])rows.push(run(`全局 5min/4s SDC100% ${seconds}s`,{sdcDetect:true,step:true,sdcCoverage:1},{recoveryAttemptSeconds:seconds},2000));
for(const success of [.99,.999])for(const seconds of [180,120,90,60,30])rows.push(run(`全局 60s/1s SDC99% 成功${success} ${seconds}s`,{sdcDetect:true,step:true,sdcCoverage:.99,fast:true},{recoveryAttemptSeconds:seconds,recoverySuccess:success},2000));
for(const delay of [120,24,6,1])rows.push(run(`组合 SDC95% 兜底${delay}h`,{...combo,sdcCoverage:.95},{sdcDelayHours:delay},2000));
for(const coverage of [.99,.995,.999])rows.push(run(`推荐复核 SDC${coverage} 全局120s`,{...combo,sdcCoverage:coverage},{recoveryAttemptSeconds:120},10000));
fs.writeFileSync(path.join(__dirname,'target90-results.json'),JSON.stringify({target:'30天正确有效产出率，非仅运行可用度',notes:['恢复时间扫描仅修改全局CKPT与亚健康恢复尝试；局部180秒、进程60秒、重执行5秒保持原值','自动恢复成功率99%、失败额外2小时，除明确标记外保持不变','组合包括60秒计算/1秒保存，不是当前300秒/4秒基线','0秒恢复为数学上限情景，不是工程承诺','达到90%的月任务比例为当前随机模型估计，不是生产SLA'],rows},null,2));
